# Generated by Django 4.2.16 on 2024-09-25 05:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDashboard',
            fields=[
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, unique=True)),
                ('folder_uid', models.CharField(max_length=128)),
                ('datasource_uid', models.CharField(max_length=128)),
                ('custom_dashboard_id', models.IntegerField()),
                ('custom_dashboard_uid', models.CharField(max_length=128)),
                ('default_dashboard_id', models.IntegerField()),
                ('default_dashboard_uid', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dashboard_index', models.IntegerField()),
                ('title', models.CharField(max_length=128)),
                ('query', models.TextField()),
                ('range_start', models.CharField(max_length=128)),
                ('range_end', models.CharField(max_length=128)),
                ('limit', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
